"""Add hourly_rate to instructors

Revision ID: d01daf287252
Revises: 2cb901f0828c
Create Date: 2025-11-30 22:37:36.026952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01daf287252'
down_revision: Union[str, None] = '2cb901f0828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('hourly_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'hourly_rate')
    # ### end Alembic commands ###
